---
- name: Setup MongoDB on the database server and configure the web server
  hosts: all
  become: yes
  tasks:
    - name: Check if the 'travelmemory' database exists
      command: >
        mongosh --quiet --eval "db.getMongo().getDBNames().includes('travelmemory')"
      register: db_check
      changed_when: false
      ignore_errors: yes
      when: "'db' in group_names"

    - name: Create 'travelmemory' database and user if it does not exist
      command: >
        mongosh --eval "db = db.getSiblingDB('travelmemory');
        db.createUser({user: 'travelmemoryuser', pwd: 'password', roles: [{ role: 'readWrite', db: 'travelmemory' }]});"
      when: "'db' in group_names and db_check.stdout != 'true'"

    - name: Change bindIp to 0.0.0.0 in MongoDB config
      lineinfile:
        path: /etc/mongod.conf
        regexp: '^ *bindIp:'
        line: '  bindIp: 0.0.0.0'
        state: present
      when: "'db' in group_names"

    - name: Restart MongoDB service
      service:
        name: mongod
        state: restarted
      when: "'db' in group_names"

    - name: Copy 'userdata.sh' to the web server
      copy:
        src: ./userdata.sh
        dest: /home/ubuntu/
      when: "'web' in group_names"

    - name: Ensure userdata.sh is executable
      file:
        path: /home/ubuntu/userdata.sh
        mode: '0755'
      when: "'web' in group_names"

    - name: Execute userdata.sh to bring up the web server
      command: /home/ubuntu/userdata.sh
      when: "'web' in group_names"
